Repository future4code/mello-cookenu15, pull requests merged in 2020-08, with the labels that each got.

#1 Push inicial com dependências e estrutura básica
  package-lock.json
  package.json
  src/index.ts
  src/services/Authenticator.ts
  src/services/HashManager.ts
  src/services/IdGenerator.ts
  tsconfig.json
Labels: Push-Inicial

#2 Push inicial com dependências e estrutura básica
  src/endpoints/anotherUser.ts
  src/endpoints/followUser.ts
  src/endpoints/getFeed.ts
  src/endpoints/getRecipe.ts
  src/endpoints/login.ts
  src/endpoints/recipe.ts
  src/endpoints/signUp.ts
  src/endpoints/unfollowUser.ts
  src/endpoints/userProfile.ts
Labels: enhancement

#10 Implementação da getUserProfile, EndPoint user/profile fucnional.
  src/data/UserDatabase.ts
  src/endpoints/userProfile.ts
  src/index.ts
Labels: enhancement

#11 endpoints unfollow e getFeed implementados
  src/data/UserDatabase.ts
  src/endpoints/followUser.ts
  src/endpoints/getFeed.ts
  src/endpoints/getRecipeById.ts
  src/endpoints/unfollowUser.ts
  src/index.ts
  src/services/Authenticator.ts
Labels: bug, enhancement

#12 Entrega Projeto Mello Cookenu 15 - Últimas alterações.
  README.md
  package.json
  src/data/UserDatabase.ts
  src/endpoints/anotherUser.ts
  src/index.ts
Labels: documentation, enhancement
